using Microsoft.EntityFrameworkCore.Migrations;
using System.Drawing;

#nullable disable

namespace FiscoSystem.Migrations
{
    public partial class InsertFisco : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '2105', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '8481', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '27101919', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '1806', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '1901', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '2106', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '27101931', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '27101932', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '24031', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '7009', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '17019100', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - ST', '1702', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '96031000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '19030000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '19041000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '19049000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '2008', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20089100', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '10082990', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '1806', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '0408', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '11042300', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '07134090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '22098990', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '96131000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '07132090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '15162000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '19019090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '07131090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '35079040', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '19024000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20031000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '35071000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '28011000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '1806', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20019000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '18050000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '18061000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20041000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20052000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '28142000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '56012110', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '28470000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20098922', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '20098921', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiveresos - NORMAL', '21069090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('zDiversos - NORMAL', '29141100', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '08062000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '12019000', '17', 'NORMAL', '00', 'SUSPENSAO')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '4901', '0', 'NORMAL', '41', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '4902', '0', 'NORMAL', '41', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '4903', '00', 'NORMAL', '41', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '40141000', '0', 'S.T', '30', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '3004', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '2008', '0', 'NORMAL', '40', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '11041900', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '48181000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '0407', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '1513', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '08023', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '15171000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '07141000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '08026', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '27111910', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '36041000', '25', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '06', '0', 'NORMAL', '40', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Outros', '12081000', '17', 'NORMAL', '0', 'SUSPENSAO')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08042020', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08131000', '17', 'NORMAL', '00', 'Aliquota zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '110220', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08011200', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08011100', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08012', '17', 'NORMAL', '0', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08013', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '11031300', '17', 'NORMAL', '00', 'aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '0901', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '21011110', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '95044000', '25', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '08039000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '081320', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - outros', '0712', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Sit.Especial - Azeite - ST', '1509', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' RAÃ‡Ã•ES   (Tipo PET, p/animais domÃ©sticos)', '2309', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '3305', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33079000', '25', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33049100', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33051000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '3359000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33043000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33049990', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '3307', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '3303', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '330720', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '330499', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33059000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33071000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '3303', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33049900', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33041000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33052000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perfumes e CosmÃ©ticos', '33043000', '25', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Toucador ou Hig Pessoal', '34011190', '17', 'NORMAL', '00', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '96190000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '33069000', 'S.T', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '39233000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '39249000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '39241000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '40149090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '70102000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '56012090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '96190000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '96032100', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '33062000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '33061000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '39249000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '39269040', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '39269090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '40149090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES (' Perf, Hig Pessoal e CosmÃ©ticos', '96190000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Perf, Hig Pessoal e CosmÃ©ticos', '33062000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Perf..Prods Farmac', '30051010', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Perf..Prods Farmac', '3005', '17', 'ST', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PEIXES', '0305', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PEIXES', '0302', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PEIXES', '0303', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PEIXES', '0304', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PEIXES', '1604', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolahcas', '19054000', '17', 'S.T', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolahcas', '19059090', '17', 'NORMAL', '20', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolahcas', '1905', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolahcas', '19052010', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolachas', '1905902', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolachas', '1905909', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolachas', '19052090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolachas', '190532', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '38089419', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '34054000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '38089419', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '63071000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '34011900', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '27101230', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '34051000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '63071000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '27101999', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '38089419', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '38249979', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '38249941', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '96039000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '38099190', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '28151200', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat Limp - Outros', '34052000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '3402', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '39232', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '34012090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '34022000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '39241000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '39249000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '68053010', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '68053090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '73231000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '28289011', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '28283019', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '32064100', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '38099190', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. Limpeza', '2828', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. de Limpeza', '28289011', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. de Limpeza', '28289019', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. de Limpeza', '32064100', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. de Limpeza', '34022000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Mat. de Limpeza', '38089414', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Massas Alimenticias', '1902', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Massas Alimenticias', '1902', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Massas Alimenticias', '1902', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados - Outros', '19019090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados - Outros', '1901', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0406', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0406', '17', 'NORMAL', '00', 'Aiquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04062000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04062000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04051000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04051000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0401', '12', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04011010', '12', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04012010', '12', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04011010', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04012010', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04039000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04039000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0402', '12', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0402', '12', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0401', '0', 'S.T', '30', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '0401', '00', 'NORMAL', '40', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04031000', '17', 'normal', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04039000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '04039000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '22029900', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Leites e Derivados', '22029900', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('LÃ¢mpadas ElÃ©tricas, Diodos e Aparelhos de iluminaÃ§Ã£o', '853650', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('LÃ¢mpadas ElÃ©tricas, Diodos e Aparelhos de iluminaÃ§Ã£o', '85041000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('LÃ¢mpadas ElÃ©tricas, Diodos e Aparelhos de iluminaÃ§Ã£o', '8539', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('LÃ¢mpadas ElÃ©tricas, Diodos e Aparelhos de iluminaÃ§Ã£o', '8540', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('LÃ¢mpadas ElÃ©tricas, Diodos e Aparelhos de iluminaÃ§Ã£o', '85395000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '07096000', '17', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '07099990', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '07099919', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '07', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '08', '00', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '07081000', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '0709', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '070310', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '0714', '0', 'NORMAL', '40', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '0701', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '08061000', '0', 'NORMAL', '40', 'Aliquiota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '08083000', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '08081000', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '08051000', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '08042010', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '08011900', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - Frutas Frescas', '0803', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti (est. Nat/resfriado)', '08094000', '0', 'NORMAL', '40', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('H.Fruti - ExceÃ§Ãµes', '0802', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '19012000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '19012000', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '19012000', '17', 'NORMAL', '20', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '19019090', '17', 'NORMAL', '20', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '19012000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '19019090', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '11010010', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '11010010', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Farinha de Trigo e Misturas', '11010010', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '0305', '17', 'NORMAL', '20', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '0302', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '0303', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '0304', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1604', '17', 'NORMAL', '20', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '15179010', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1508', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1509', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1510', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1511', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1512', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1513', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1514', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '1507', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '15152910', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '15151900', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '15119000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '11022000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '07133319', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '07133329', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '07133399', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '0713', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '11022000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '11062000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '0901', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '100620', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '100630', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '07032090', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '17011400', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '17019900', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '17011400', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Cesta BÃ¡sica', '17019900', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0504', '17', 'NORMAL', '20', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '05100010', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '05069000', '17', 'NORMAL', '20', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '05100010', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '05069000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '15011000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '1601', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '1602', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02102000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02101', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0203', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0206', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0209', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02101', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02109900', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '1501', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0207', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0209', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02071', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02072', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02109900', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '15021019', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '15029000', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '02102000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '1502', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0201', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0202', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0204', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Carnes e Derivados', '0206', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22086000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '2205', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22060090', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22085000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22089000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '220720', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22084000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '2204', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '2205', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '2206', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '2207', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '2208', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22060010', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22082000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '220830', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22082000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Quentes', '22087000', '27', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22021000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22021000', '17', 'NORMAL', '00', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22029900', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '2202', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22029100', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22030000', '27', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '2106', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22021000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Bebidas Frias', '22011000', '17', 'S.T', '60', 'Aliquota Zero')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Aparelhos e LÃ¢minas de Barbear', '82121020', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Aparelhos e LÃ¢minas de Barbear', '82022010', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Ãlcool', '38089429', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Ãlcool', '22079000', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Ãlcool', '22089000', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Ãlcool', '220710', '27', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('Ãlcool', '22072010', '17', 'S.T', '60', 'Monofasica')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos e Bolahcas', '19059090', '17', 'NORMAL', '00', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos E Bolachas', '1905', '17', 'S.T', '60', 'NORMAL')");
            migrationBuilder.Sql("INSERT INTO tabelafisco (Grupo, Ncm, Aliquota, Forma_Tributacao, CST, Forma_Pis_Cofins) VALUES ('PÃ£es, Biscoitos E Bolachas', '1905', '17', 'NORMAL', '20', 'NORMAL')");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
